[project]
name="iati2json"
description = "Opinionated JSON to CSV converter"
readme="README.md"
repository="https://github.com/kindly/iati2json"
license = {text= "MIT"}

[build-system]
requires = ["maturin>=0.11,<0.12"]
build-backend = "maturin"

